#! /bin/sh
sxhkd &

bspc monitor -d term media web chat code help show_off
bspc desktop web -l monocle

bspc config initial_polarity second_child
#┌──────────────────────────────────────────────────────────────────┐
#│                              outlooking                          │
#└──────────────────────────────────────────────────────────────────┘
bspc config normal_border_color "#10151b"
bspc config focused_border_color "#98d1ce"
bspc config presel_feedback_color "#aaaaaa"
bspc config border_width         1 
bspc config window_gap           25

bspc config split_ratio          0.52
bspc config gapless_monocle      true

#┌───────────────────────────────────────────────────────────────────┐
#│                              mouse                                │
#└───────────────────────────────────────────────────────────────────┘
# press down the windows key and mouse left button to move the window
bspc config pointer_action1 move
# none
bspc config pointer_action2 none
# press down the windows key and mouse left button to resize the window
bspc config pointer_action3 resize_corner

bspc config click_to_focus true
#bspc config ignore_ewmh_focus true

#┌───────────────────────────────────────────────────────────────────┐
#│                              rule                                 │
#└───────────────────────────────────────────────────────────────────┘
#bspc rule -a "*" split_dir=east
bspc rule -a Zathura split_dir=east focus=off state=tiled

#bspc rule -a Gimp desktop=^8 state=floating follow=on
#bspc rule -a Google-chrome desktop=^1
#bspc rule -a Genymotion desktop=^3

#bspc rule -a TelegramDesktop desktop=^3
#bspc rule -a Subl desktop=^4
#bspc rule -a Spotify desktop=^5
#bspc rule -a Lmms desktop=^5
#bspc rule -a mplayer2 state=floating
#bspc rule -a Gedit state=floating
#bspc rule -a Eog state=floating
#bspc rule -a Nautilus state=floating
#bspc rule -a File-roller state=floating
#bspc rule -a Gnome-system-monitor state=floating

#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off

xsetroot -cursor_name left_ptr
 
#┌───────────────────────────────────────────────────────────────────┐
#│                           autostart                               │
#└───────────────────────────────────────────────────────────────────┘
xrdb -merge ~/.Xdefaults

feh --randomize --bg-fill ~/Pictures/wallpaper

pgrep -u "$USER" compton >/dev/null || \
    compton --config ~/.compton.conf -b

pgrep -u "$USER" redshift >/dev/null || \
    redshift &

#lantern

nvim-qt
#gnome-terminal --hide-menubar -e fish

# set `wm-restack = bspwm` to avoid visible polybar on fullscreen
#. ~/.config/polybar/launch.sh &
